package com.app.model;

// Generated 2016-3-21 11:16:01 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Zan generated by hbm2java
 */
@Entity
@Table(name = "likeurl", catalog = "lovenote")
public class LikeUrl implements java.io.Serializable {
	private Integer id;
	private Integer uid;
	private String url;
	private String title;
	private String date;
	private String classify;

	public LikeUrl(Integer id) {
		super();
		this.id = id;
	}

	public LikeUrl() {
		this.uid = 1;
		this.url = "";
		this.title = "";
		this.date = "";
		this.classify = "默认";
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "uid")
	public Integer getUid() {
		return uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "url")
	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "title")
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "date")
	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "classify")
	public String getClassify() {
		return classify;
	}

	public void setClassify(String classify) {
		this.classify = classify;
	}

}
