package com.app.model;

// Generated 2016-3-21 11:16:01 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Relation generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "lovenote")
public class Message implements java.io.Serializable {

	private Integer id;
	private String name;
	private String ip;
	private String content;
	private Date time;

	public Message() {
		this.name = "";
		this.ip = "";
		this.content = "";
		this.time = new Date();
	}

	public Message(Integer id) {
		this.id = id;
	}

	public Message(Integer id, String name, String ip, String content, Date time) {
		super();
		this.id = id;
		this.name = name;
		this.ip = ip;
		this.content = content;
		this.time = time;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ip")
	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "content")
	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 19)
	public Date getTime() {
		return time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
