package com.app.model;
// Generated 2016-3-21 11:16:01 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Money generated by hbm2java
 */
@Entity
@Table(name = "money", catalog = "lovenote")
public class Money implements java.io.Serializable {

	private Integer id;
	private String uname;
	private Integer inout2;
	private String type;
	private Date createtime;
	private String instruction;
	private Float money;
	private String extendone;
	private String extendtwo;
	private Integer isdelete;

	public Money(){
		this.uname="";
		this.instruction="";
		this.type="";
		this.extendone="";
		this.extendtwo="";
		this.inout2=0;
		this.money=(float) 0;
		this.isdelete=0;
		this.createtime = new Date();
	}
	public Money(Integer id) {
		this.id = id;
	}

	public Money(String uname, Integer inout2, String type, Date createtime, String instruction, Float money,
			String extendone, String extendtwo, Integer isdelete) {
		this.uname = uname;
		this.inout2 = inout2;
		this.type = type;
		this.createtime = createtime;
		this.instruction = instruction;
		this.money = money;
		this.extendone = extendone;
		this.extendtwo = extendtwo;
		this.isdelete = isdelete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "uname", length = 30)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "inout2")
	public Integer getInout2() {
		return this.inout2;
	}

	public void setInout2(Integer inout2) {
		this.inout2 = inout2;
	}

	@Column(name = "type", length = 15)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "instruction")
	public String getInstruction() {
		return this.instruction;
	}

	public void setInstruction(String instruction) {
		this.instruction = instruction;
	}

	@Column(name = "money", precision = 15, scale = 0)
	public Float getMoney() {
		return this.money;
	}

	public void setMoney(Float money) {
		this.money = money;
	}

	@Column(name = "extendone", length = 15)
	public String getExtendone() {
		return this.extendone;
	}

	public void setExtendone(String extendone) {
		this.extendone = extendone;
	}

	@Column(name = "extendtwo", length = 15)
	public String getExtendtwo() {
		return this.extendtwo;
	}

	public void setExtendtwo(String extendtwo) {
		this.extendtwo = extendtwo;
	}

	@Column(name = "isdelete")
	public Integer getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

}
