package com.app.model;

// Generated 2016-3-21 11:16:01 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Note generated by hbm2java
 */
@Entity
@Table(name = "note", catalog = "lovenote")
public class Note implements java.io.Serializable {

	private Integer id;
	private String uname;
	private String title;
	private String content;
	private Date createtime;
	private String type;
	// 用做收藏文的网址
	private String extendone;
	private String extendtwo;
	private Integer isdelete;
	private String part;
	private Integer click;
	private Integer likenum;
	private Integer unlike;
	private Set<Review> reviews = new HashSet<Review>(0);

	public Note() {
		this.click = 0;
		this.unlike = 0;
		this.likenum = 0;
		this.isdelete = 0;
		this.uname = "";
		this.title = "";
		this.content = "";
		this.type = "";
		this.extendone = "";
		this.extendtwo = "";
		this.part = "";
		this.createtime = new Date();
	}

	public Note(Integer id) {
		this.id = id;
	}

	public Note(String uname, String title, String content, Date createtime,
			String type, String extendone, String extendtwo, Integer isdelete,
			String part, Integer click, Integer likenum, Integer unlike,
			Set<Review> reviews) {
		this.uname = uname;
		this.title = title;
		this.content = content;
		this.createtime = createtime;
		this.type = type;
		this.extendone = extendone;
		this.extendtwo = extendtwo;
		this.isdelete = isdelete;
		this.part = part;
		this.click = click;
		this.likenum = likenum;
		this.unlike = unlike;
		this.reviews = reviews;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "uname", length = 64)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "title", length = 225)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "type", length = 15)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "extendone", length = 64)
	public String getExtendone() {
		return this.extendone;
	}

	public void setExtendone(String extendone) {
		this.extendone = extendone;
	}

	@Column(name = "extendtwo", length = 64)
	public String getExtendtwo() {
		return this.extendtwo;
	}

	public void setExtendtwo(String extendtwo) {
		this.extendtwo = extendtwo;
	}

	@Column(name = "isdelete")
	public Integer getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	@Column(name = "part")
	public String getPart() {
		return this.part;
	}

	public void setPart(String part) {
		this.part = part;
	}

	@Column(name = "click")
	public Integer getClick() {
		return this.click;
	}

	public void setClick(Integer click) {
		this.click = click;
	}

	@Column(name = "likenum")
	public Integer getLikenum() {
		return this.likenum;
	}

	public void setLikenum(Integer likenum) {
		this.likenum = likenum;
	}

	@Column(name = "unlike")
	public Integer getUnlike() {
		return this.unlike;
	}

	public void setUnlike(Integer unlike) {
		this.unlike = unlike;
	}

	/*
	 * @OneToMany(fetch = FetchType.EAGER, mappedBy = "note") public Set<Review>
	 * getReviews() { return this.reviews; }
	 * 
	 * public void setReviews(Set<Review> reviews) { this.reviews = reviews; }
	 */

}
