package com.app.model;
// Generated 2016-3-21 11:16:01 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Zan generated by hbm2java
 */
@Entity
@Table(name = "record", catalog = "lovenote")
public class Record implements java.io.Serializable {

	private Integer id;
	private String ip;
	private String user;
	private Integer searchnum;
	private Integer indexnum;
	private Date startdate;
	private Date enddate;
	private String device;

	public Record(){
		this.ip="";
		this.user="";
		this.searchnum = 0;
		this.indexnum = 0;
		this.startdate = new Date();
		this.enddate = new Date();
		this.device="";
	}
	public Record(Integer id) {
		this.id = id;
	}
	
	public Record(String ip,String user,Integer searchnum, Integer indexnum,Date startdate,Date enddate,String device) {
		this.searchnum = searchnum;
		this.indexnum = indexnum;
		this.user=user;
		this.ip=ip;
		this.device=device;
		this.startdate = startdate;
		this.enddate = enddate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "ip", length = 15)
	public String getIp() {
		return ip;
	}
	public void setIp(String ip) {
		this.ip = ip;
	}
	
	@Column(name = "user", length = 225)
	public String getUser() {
		return user;
	}
	public void setUser(String user) {
		this.user = user;
	}
	
	@Column(name = "searchnum")
	public Integer getSearchnum() {
		return searchnum;
	}
	public void setSearchnum(Integer searchnum) {
		this.searchnum = searchnum;
	}
	
	@Column(name = "indexnum")
	public Integer getIndexnum() {
		return indexnum;
	}
	public void setIndexnum(Integer indexnum) {
		this.indexnum = indexnum;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startdate", length = 19)
	public Date getStartdate() {
		return startdate;
	}
	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "enddate", length = 19)
	public Date getEnddate() {
		return enddate;
	}
	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}
	
	@Column(name = "device", length = 50)
	public String getDevice() {
		return device;
	}
	public void setDevice(String device) {
		this.device = device;
	}

}
