package com.app.model;
// Generated 2016-3-21 11:16:01 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Relation generated by hbm2java
 */
@Entity
@Table(name = "relation", catalog = "lovenote")
public class Relation implements java.io.Serializable {

	private Integer id;
	private Integer toid;
	private Integer fromid;

	public Relation() {
		
	}
	
	public Relation(Integer id) {
		this.id = id;
	}
	
	public Relation(Integer toid, Integer fromid) {
		this.toid = toid;
		this.fromid = fromid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "toid")
	public Integer getToid() {
		return this.toid;
	}

	public void setToid(Integer toid) {
		this.toid = toid;
	}

	@Column(name = "fromid")
	public Integer getFromid() {
		return this.fromid;
	}

	public void setFromid(Integer fromid) {
		this.fromid = fromid;
	}

}
