package com.app.model;
// Generated 2016-3-21 11:16:01 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name = "review", catalog = "lovenote")
public class Review implements java.io.Serializable {

	private Integer id;
	//private Note note;
	private String uname;
	private Integer noteid;
	private String content;
	private Date time;
	private String extendone;

	public Review() {
		this.extendone = "";
		this.time = new Date();
	}
	public Review(Integer id) {
		this.id = id;
	}
	public Review(String uname,Integer noteid, String content, Date time, String extendone) {
		this.noteid = noteid;
		this.uname = uname;
		this.content = content;
		this.time = time;
		this.extendone = extendone;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "noteid")
	public Integer getNoteid() {
		return this.noteid;
	}

	public void setNoteid(Integer noteid) {
		this.noteid = noteid;
	}
	/*@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "noteid")
	public Note getNote() {
		return this.note;
	}

	public void setNote(Note note) {
		this.note = note;
	}*/

	@Column(name = "uname",length = 30)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "extendone", length = 15)
	public String getExtendone() {
		return this.extendone;
	}

	public void setExtendone(String extendone) {
		this.extendone = extendone;
	}

}
