package com.app.model;
// Generated 2016-3-21 11:16:01 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name = "type", catalog = "lovenote")
public class Type implements java.io.Serializable {

	private Integer id;
	private String name;
	private String classify;
	private String extendone;
	private Integer isdelete;

	public Type(){
		this.extendone="";
		this.name="";
		this.classify="";
		isdelete=0;
	}

	public Type(Integer id) {
		this.id = id;
	}
	
	public Type(String name, String classify, String extendone, Integer isdelete) {
		this.name = name;
		this.classify = classify;
		this.extendone = extendone;
		this.isdelete = isdelete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "classify", length = 15)
	public String getClassify() {
		return this.classify;
	}

	public void setClassify(String classify) {
		this.classify = classify;
	}

	@Column(name = "extendone", length = 15)
	public String getExtendone() {
		return this.extendone;
	}

	public void setExtendone(String extendone) {
		this.extendone = extendone;
	}

	@Column(name = "isdelete")
	public Integer getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

}
