package com.app.model;
// Generated 2016-3-21 11:16:01 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Zan generated by hbm2java
 */
@Entity
@Table(name = "zan", catalog = "lovenote")
public class Zan implements java.io.Serializable {

	private Integer id;
	private String uname;
	private Integer noteid;
	private Integer islike;
	private String extendone;

	public Zan(){
		this.noteid=0;
		this.islike=1;
		this.uname="";
		this.extendone="";
	}
	public Zan(Integer id) {
		this.id = id;
	}
	
	public Zan(String uname, Integer noteid, Integer islike, String extendone) {
		this.uname = uname;
		this.noteid = noteid;
		this.islike = islike;
		this.extendone = extendone;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "uname", length = 30)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "noteid")
	public Integer getNoteid() {
		return this.noteid;
	}

	public void setNoteid(Integer noteid) {
		this.noteid = noteid;
	}

	@Column(name = "islike")
	public Integer getIslike() {
		return this.islike;
	}

	public void setIslike(Integer islike) {
		this.islike = islike;
	}

	@Column(name = "extendone", length = 10)
	public String getExtendone() {
		return this.extendone;
	}

	public void setExtendone(String extendone) {
		this.extendone = extendone;
	}

}
